#!/bin/bash

# =============================================================================
# Symlink files
# By Brad Parbs <brad@bradparbs.com> and Justin Sternberg <me@jtsternberg.com>
# https://github.com/jtsternberg/Dot-Files/blob/master/symdotfiles
#
# Version 1.0.0
#
# Creates symlinks to all files in the current directory
# to the directory above it.
#
# Usage:
# cd to this script's directory and..
# sh symdotfiles
# =============================================================================

THIS_SCRIPT=`basename $0`
rm -rf .DS_Store
WORKING_DIR=`pwd`
shopt -s dotglob
ALLFILES=*

echo "Making those symlinks"
for file in $ALLFILES; do
	if
		[ $THIS_SCRIPT != $file ] &&
		[ '.git' != $file ] &&
		[ 'zsh-custom' != $file ] &&
		[ 'misc' != $file ] &&
		[ '.gitmodules' != $file ] &&
		[ '.gitignore' != $file ] &&
		[ '.aliases' != $file ] &&
		[ '.exports' != $file ] &&
		[ '.functions' != $file ] &&
		[ 'dotfiles.sublime-project' != $file ] &&
		[ 'dotfiles.sublime-workspace' != $file ]

		then
			echo "Processing $file file..."
			rm ../$file
			ln -s $WORKING_DIR/$file ../$file
	fi
done
